---
- name: Get apt updates.
  apt:
    update_cache: yes
    cache_valid_time: "{{ aptget_update_cache_valid_time }}"
  when: aptget_update

- name: Simple apt upgrade.
  shell: apt-get upgrade -y
  when: aptget_upgrade

